config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :listings
  get 'pages/listings'

  get 'pages/about'

  get 'pages/contact'

  get     'search'   =>      'listings#index'

end

app/models/age.rb
class Age < ActiveRecord::Base
	has_many :listings
end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :colorings
	has_many :listings, through: :colorings
end

app/models/coloring.rb
class Coloring < ActiveRecord::Base
	belongs_to :listing
	belongs_to :color
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :room
	belongs_to :age
    has_attached_file :photo, :styles => { :medium => "250x250>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
	has_many :colorings
	has_many :colors, through: :colorings
def self.search(search)
  if search.present?
    where('name LIKE ?', "%#{search}%")
  else
    where(true)
  end
end

end

app/models/price.rb
class Price < ActiveRecord::Base
	has_many :listings
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
    if params[:search]
    @listings = Listing.search(params[:search])
  else
    @listings = Listing.all
  end
end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :Price, :room_id, :age_id, :photo, { :color_ids => [] })
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
<p>Copyright 2015</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/listings">Recycle.it</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About <span class="sr-only">(current)</span></a></li>
        <li><a href="/pages/contact">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Sign up</a></li>
            <li><a href="#">Sign In</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recycledemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>


	<%= yield %>
	<div class="row">
	<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, html: { multipart: true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>
      <ul>
        <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :room_id %><br>
    <%= f.select(:room_id,
    options_from_collection_for_select(Room.all, :id, :name, @listing.room_id), {}, { :class => 'form-control' }) %>
  </div>
  <div class="form-group">
    <%= f.label :age_id %><br>
    <%= f.select(:age_id,
    options_from_collection_for_select(Age.all, :id, :name, @listing.age_id), {}, { :class => 'form-control' }) %>
  </div>
  <div class="form-group">
    <%= f.label :colors %><br>
    <label ="checkbox">
    <%= collection_check_boxes(:listing, :color_ids, Color.all, :id, :name) do |b| %>
    <div class="row">
      <%= b.label(class: "checkbox") do %>
      <div class="col-xs-4">
        <%= b.check_box(class: "check_box") %>
      </div>
      <div class="col-xs-8">
        <%= b.object.name %>
      </div>
      <% end %>
    </div>
    <% end %>
    </label>
  </div>
  <div class="form-group">
    <%= f.label :Price %><br>
    <%= f.text_field :Price, class: "form-control" %>
  </div>
  <div class="form-group">Upload Image
    <%= f.label :photo %><br>
    <%= f.file_field :photo, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
</div>
</div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
<%= form_for @listing, :url => listings_path, :html => { :multipart => true } do |form| %>
<% end %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="hero">
  <div class="container-fluid"><a href="/listings">
    <div class="search">
      <h2>Find furniture</h2>
      <p><a href="/listings">See all listings</a></p>
      <%= form_tag(listings_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Listings" %>
<%= submit_tag "Search" %>
<% end %>
    </div>
    <h1 class="hero_header">Re.cycle It</h1>
    <h4>Buy & Sell furniture in your city</h4>
      <img src="http://res.cloudinary.com/re-cycle-it/image/upload/o_100/v1431746110/chairs_krdvwu.jpg" class="img-responsive"></a>
  </div>
</div>
  <div class="row">
      <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
      <%= image_tag listing.photo.url %>
        <div class="caption">
          <h3><%= listing.name %></h3>
          <p><%= number_to_currency(listing.Price) %></p>
          <%= link_to 'Show', listing, class: "btn btn-link" %>
          <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>
          <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-link" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

<%= form_for @listing, :url => listings_path, :html => { :multipart => true } do |form| %>
<% end %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
		<%= image_tag @listing.photo.url %>
	</div>
</div>
	<div class="col-md-6">
		<h3><%= @listing.name %></h3>
		<p><%= number_to_currency(@listing.Price) %><p>
		<p><%= @listing.description %></p>
	</div>
</div>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>
</div>

app/views/pages/about.html.erb
<html>
<body>
	<head>
    <link rel="application.scss" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  </head>
 <div class="hero">
	<div class="container-fluid">
		<h1 class="about_header">About Re.cycle It
		</h1>
			<img src="http://res.cloudinary.com/re-cycle-it/image/upload/v1431389892/desksmall_fadzmm.jpg
" class="img-responsive">
	</div>
</div>
<div class="founders">
	<div class="row">
		<div class="col-md-6">
			<h2>About the Founders</h2>
			<p>The founders have a passion for furniture and bringing beautiful things into your home.</p>
		</div>
		<div class="col-md-6">
			<img src="http://res.cloudinary.com/re-cycle-it/image/upload/c_scale,e_grayscale,w_334/v1431390093/founders_dzrr2a.jpg" class="img-founders">
		</div>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>